import 'package:drift/drift.dart';

/// Complete canonical master-data seed for offline terminal initialization.
///
/// Implements Objective 3: Complete Offline Canonical Seed.
/// A brand-new offline terminal starts with the full canonical catalog
/// required for cashier operations without depending on an initial remote sync.
///
/// All records use deterministic, static UUIDs identical to Supabase dev/prod baselines.
/// All statements use `INSERT OR IGNORE` for idempotency across restarts.
/// Zero `sync_operations` outbox records are generated by this seed.
///
/// IMPORTANT: This seed is strictly OPT-IN. It is NOT executed on normal
/// startup; a fresh install starts with an empty local database and master
/// data is created by the user through the app (and pushed via the normal
/// sync/outbox flow). Enable explicitly for development/tests with:
/// `flutter run --dart-define=ENABLE_CANONICAL_SEED=true`
/// (independent of `ENABLE_DEV_TEST_DATA`).
class SeedData {
  /// Last sequence emitted by the canonical remote master-data baseline.
  ///
  /// The baseline contains 35 sync changes: aggregate service and storage
  /// changes include their junction rows. A canonical local database starts
  /// at this cursor so it does not replay its own bootstrap history.
  static const int canonicalBaselineSequence = 35;

  /// Compile-time opt-in flag for canonical seeding. Defaults to `false`.
  static const bool isEnabled = bool.fromEnvironment(
    'ENABLE_CANONICAL_SEED',
    defaultValue: false,
  );

  // Singleton Business Settings
  static const String defaultBusinessSettingsId =
      '00000000-0000-0000-0000-000000000001';

  // Item Types (4 canonical rows)
  static const String typeClothingId = '00000000-0000-0000-0001-000000000001';
  static const String typeBlanketsId = '00000000-0000-0000-0001-000000000002';
  static const String typeCarpetsId = '00000000-0000-0000-0001-000000000003';
  static const String typeCoversId = '00000000-0000-0000-0001-000000000004';

  static const List<Map<String, String>> defaultItemTypes = [
    {'id': typeClothingId, 'name': 'ملابس'},
    {'id': typeBlanketsId, 'name': 'بطاطين'},
    {'id': typeCarpetsId, 'name': 'سجاد'},
    {'id': typeCoversId, 'name': 'أغطية'},
  ];

  // Expense Categories (7 canonical rows)
  static const List<Map<String, String>> defaultExpenseCategories = [
    {'id': '00000000-0000-0000-0002-000000000001', 'name': 'كهرباء'},
    {'id': '00000000-0000-0000-0002-000000000002', 'name': 'مياه'},
    {'id': '00000000-0000-0000-0002-000000000003', 'name': 'منظفات'},
    {'id': '00000000-0000-0000-0002-000000000004', 'name': 'صيانة'},
    {'id': '00000000-0000-0000-0002-000000000005', 'name': 'مستلزمات'},
    {'id': '00000000-0000-0000-0002-000000000006', 'name': 'نقل'},
    {'id': '00000000-0000-0000-0002-000000000007', 'name': 'أخرى'},
  ];

  // Services (5 canonical rows)
  static const String srvWashIronId = '00000000-0000-0000-0002-000000000001';
  static const String srvDryCleanId = '00000000-0000-0000-0002-000000000002';
  static const String srvCarpetWashId = '00000000-0000-0000-0002-000000000003';
  static const String srvBlanketId = '00000000-0000-0000-0002-000000000004';
  static const String srvCoverId = '00000000-0000-0000-0002-000000000005';

  static const List<Map<String, String>> defaultServices = [
    {'id': srvWashIronId, 'name': 'غسيل ومكوى', 'description': 'خدمة تجريبية'},
    {'id': srvDryCleanId, 'name': 'دراي كلين', 'description': 'خدمة تجريبية'},
    {'id': srvCarpetWashId, 'name': 'غسيل سجاد', 'description': 'خدمة تجريبية'},
    {'id': srvBlanketId, 'name': 'تنظيف بطاطين', 'description': 'خدمة تجريبية'},
    {'id': srvCoverId, 'name': 'غسيل أغطية', 'description': 'خدمة تجريبية'},
  ];

  // Service Item Types (5 canonical rows)
  static const List<Map<String, dynamic>> defaultServiceItemTypes = [
    {
      'id': '00000000-0000-0000-0008-000000000001',
      'service_id': srvWashIronId,
      'item_type_id': typeClothingId,
      'pricing_type': 'per_piece',
      'price': 2500,
    },
    {
      'id': '00000000-0000-0000-0008-000000000002',
      'service_id': srvDryCleanId,
      'item_type_id': typeClothingId,
      'pricing_type': 'per_piece',
      'price': 4500,
    },
    {
      'id': '00000000-0000-0000-0008-000000000003',
      'service_id': srvCarpetWashId,
      'item_type_id': typeCarpetsId,
      'pricing_type': 'per_square_meter',
      'price': 6000,
    },
    {
      'id': '00000000-0000-0000-0008-000000000004',
      'service_id': srvBlanketId,
      'item_type_id': typeBlanketsId,
      'pricing_type': 'per_piece',
      'price': 8000,
    },
    {
      'id': '00000000-0000-0000-0008-000000000005',
      'service_id': srvCoverId,
      'item_type_id': typeCoversId,
      'pricing_type': 'per_piece',
      'price': 3500,
    },
  ];

  // Carpet Sizes (3 canonical rows)
  static const String carpetSize2x3Id = '00000000-0000-0000-0007-000000000001';
  static const String carpetSize1_5x2Id =
      '00000000-0000-0000-0007-000000000002';
  static const String carpetSize1x4Id = '00000000-0000-0000-0007-000000000003';

  static const List<Map<String, dynamic>> defaultCarpetSizes = [
    {'id': carpetSize2x3Id, 'length': 2.0, 'width': 3.0, 'area': 6.0},
    {'id': carpetSize1_5x2Id, 'length': 1.5, 'width': 2.0, 'area': 3.0},
    {'id': carpetSize1x4Id, 'length': 1.0, 'width': 4.0, 'area': 4.0},
  ];

  // Storage Locations (5 canonical rows)
  static const String locRackA1Id = '00000000-0000-0000-0006-000000000001';
  static const String locRackA2Id = '00000000-0000-0000-0006-000000000002';
  static const String locRackB1Id = '00000000-0000-0000-0006-000000000003';
  static const String locCarpetSectionId =
      '00000000-0000-0000-0006-000000000004';
  static const String locBlanketSectionId =
      '00000000-0000-0000-0006-000000000005';

  static const List<Map<String, String>> defaultStorageLocations = [
    {'id': locRackA1Id, 'name': 'رف أ-1'},
    {'id': locRackA2Id, 'name': 'رف أ-2'},
    {'id': locRackB1Id, 'name': 'رف ب-1'},
    {'id': locCarpetSectionId, 'name': 'قسم السجاد 1'},
    {'id': locBlanketSectionId, 'name': 'قسم البطاطين 1'},
  ];

  // Storage Location Item Types (9 canonical junction rows)
  static const List<Map<String, String>> defaultStorageLocationItemTypes = [
    {
      'id': '00000000-0000-0000-0008-000000000001',
      'storage_location_id': locRackA1Id,
      'item_type_id': typeClothingId,
    },
    {
      'id': '00000000-0000-0000-0008-000000000002',
      'storage_location_id': locRackA1Id,
      'item_type_id': typeCoversId,
    },
    {
      'id': '00000000-0000-0000-0008-000000000003',
      'storage_location_id': locRackA2Id,
      'item_type_id': typeClothingId,
    },
    {
      'id': '00000000-0000-0000-0008-000000000004',
      'storage_location_id': locRackA2Id,
      'item_type_id': typeCoversId,
    },
    {
      'id': '00000000-0000-0000-0008-000000000005',
      'storage_location_id': locRackB1Id,
      'item_type_id': typeClothingId,
    },
    {
      'id': '00000000-0000-0000-0008-000000000006',
      'storage_location_id': locRackB1Id,
      'item_type_id': typeCoversId,
    },
    {
      'id': '00000000-0000-0000-0008-000000000007',
      'storage_location_id': locCarpetSectionId,
      'item_type_id': typeCarpetsId,
    },
    {
      'id': '00000000-0000-0000-0008-000000000008',
      'storage_location_id': locBlanketSectionId,
      'item_type_id': typeBlanketsId,
    },
    {
      'id': '00000000-0000-0000-0008-000000000009',
      'storage_location_id': locBlanketSectionId,
      'item_type_id': typeCoversId,
    },
  ];

  // Item Definitions (10 canonical rows)
  static const String idefShirtId = '00000000-0000-0000-0005-000000000001';
  static const String idefPantsId = '00000000-0000-0000-0005-000000000002';
  static const String idefSuitId = '00000000-0000-0000-0005-000000000003';
  static const String idefSingleBlanketId =
      '00000000-0000-0000-0005-000000000004';
  static const String idefDoubleBlanketId =
      '00000000-0000-0000-0005-000000000005';
  static const String idefWoolCarpetId = '00000000-0000-0000-0005-000000000006';
  static const String idefRunnerCarpetId =
      '00000000-0000-0000-0005-000000000007';
  static const String idefDuvetCoverId = '00000000-0000-0000-0005-000000000008';
  static const String idefBedspreadId = '00000000-0000-0000-0005-000000000009';
  static const String idefSilkCarpetId = '00000000-0000-0000-0005-000000000010';

  static const List<Map<String, String>> defaultItemDefinitions = [
    {'id': idefShirtId, 'item_type_id': typeClothingId, 'name': 'قميص'},
    {'id': idefPantsId, 'item_type_id': typeClothingId, 'name': 'بنطلون'},
    {'id': idefSuitId, 'item_type_id': typeClothingId, 'name': 'بدلة'},
    {
      'id': idefSingleBlanketId,
      'item_type_id': typeBlanketsId,
      'name': 'بطانية مفرد',
    },
    {
      'id': idefDoubleBlanketId,
      'item_type_id': typeBlanketsId,
      'name': 'بطانية دبل',
    },
    {
      'id': idefWoolCarpetId,
      'item_type_id': typeCarpetsId,
      'name': 'سجادة صوف',
    },
    {'id': idefRunnerCarpetId, 'item_type_id': typeCarpetsId, 'name': 'مشاية'},
    {'id': idefDuvetCoverId, 'item_type_id': typeCoversId, 'name': 'غطاء لحاف'},
    {'id': idefBedspreadId, 'item_type_id': typeCoversId, 'name': 'كوفرتة'},
    {
      'id': idefSilkCarpetId,
      'item_type_id': typeCarpetsId,
      'name': 'سجادة حرير',
    },
  ];

  static Future<void> seedInitialData(GeneratedDatabase db) async {
    final nowTimestamp = DateTime.now().toUtc().millisecondsSinceEpoch ~/ 1000;

    // 1. Seed BusinessSettings (exactly 1 record, idempotent)
    await db.customStatement(
      'INSERT OR IGNORE INTO business_settings '
      '(id, business_name, tax_enabled, tax_rate, created_at, updated_at) '
      'VALUES (?, ?, ?, ?, ?, ?);',
      [defaultBusinessSettingsId, '', 0, 0.0, nowTimestamp, nowTimestamp],
    );

    // 2. Seed Default ItemTypes (4 types, idempotent)
    for (final itemType in defaultItemTypes) {
      await db.customStatement(
        'INSERT OR IGNORE INTO item_types '
        '(id, name, is_active, created_at, updated_at) '
        'VALUES (?, ?, ?, ?, ?);',
        [itemType['id'], itemType['name'], 1, nowTimestamp, nowTimestamp],
      );
    }

    // 3. Seed Default ExpenseCategories (7 categories, idempotent)
    for (final category in defaultExpenseCategories) {
      await db.customStatement(
        'INSERT OR IGNORE INTO expense_categories '
        '(id, name, is_active, created_at, updated_at) '
        'VALUES (?, ?, ?, ?, ?);',
        [category['id'], category['name'], 1, nowTimestamp, nowTimestamp],
      );
    }

    // 4. Seed SyncState at the canonical remote baseline. This row is local
    // metadata and must not create an outbox operation.
    await db.customStatement(
      'INSERT OR IGNORE INTO sync_state '
      '(id, last_applied_sequence, updated_at) '
      'VALUES (?, ?, ?);',
      ['singleton', canonicalBaselineSequence, nowTimestamp],
    );

    // 5. Seed Services (5 canonical services, idempotent)
    for (final service in defaultServices) {
      await db.customStatement(
        'INSERT OR IGNORE INTO services '
        '(id, name, description, is_active, created_at, updated_at) '
        'VALUES (?, ?, ?, 1, ?, ?);',
        [
          service['id'],
          service['name'],
          service['description'],
          nowTimestamp,
          nowTimestamp,
        ],
      );
    }

    // 6. Seed Service Item Types (5 canonical pricing configurations, idempotent)
    for (final sit in defaultServiceItemTypes) {
      await db.customStatement(
        'INSERT OR IGNORE INTO service_item_types '
        '(id, service_id, item_type_id, pricing_type, price, created_at, updated_at) '
        'VALUES (?, ?, ?, ?, ?, ?, ?);',
        [
          sit['id'],
          sit['service_id'],
          sit['item_type_id'],
          sit['pricing_type'],
          sit['price'],
          nowTimestamp,
          nowTimestamp,
        ],
      );
    }

    // 7. Seed Carpet Sizes (3 canonical sizes, idempotent)
    for (final cs in defaultCarpetSizes) {
      await db.customStatement(
        'INSERT OR IGNORE INTO carpet_sizes '
        '(id, length, width, area, is_active, created_at, updated_at) '
        'VALUES (?, ?, ?, ?, 1, ?, ?);',
        [
          cs['id'],
          cs['length'],
          cs['width'],
          cs['area'],
          nowTimestamp,
          nowTimestamp,
        ],
      );
    }

    // 8. Seed Storage Locations (5 canonical locations, idempotent)
    for (final loc in defaultStorageLocations) {
      await db.customStatement(
        'INSERT OR IGNORE INTO storage_locations '
        '(id, name, is_active, created_at, updated_at) '
        'VALUES (?, ?, 1, ?, ?);',
        [loc['id'], loc['name'], nowTimestamp, nowTimestamp],
      );
    }

    // 9. Seed Storage Location Item Types (9 canonical junction rows, idempotent)
    for (final slit in defaultStorageLocationItemTypes) {
      await db.customStatement(
        'INSERT OR IGNORE INTO storage_location_item_types '
        '(id, storage_location_id, item_type_id, created_at) '
        'VALUES (?, ?, ?, ?);',
        [
          slit['id'],
          slit['storage_location_id'],
          slit['item_type_id'],
          nowTimestamp,
        ],
      );
    }

    // 10. Seed Item Definitions (10 canonical items, idempotent)
    for (final def in defaultItemDefinitions) {
      await db.customStatement(
        'INSERT OR IGNORE INTO item_definitions '
        '(id, item_type_id, name, is_active, created_at, updated_at) '
        'VALUES (?, ?, ?, 1, ?, ?);',
        [
          def['id'],
          def['item_type_id'],
          def['name'],
          nowTimestamp,
          nowTimestamp,
        ],
      );
    }

    // Explicit Invariant:
    // customers, orders, order_items, payments, expenses, storage_records,
    // and sync_operations are NEVER seeded. They remain strictly empty.
  }
}
